/*
 * TeleStax, Open Source Cloud Communications
 * Copyright 2011-2013, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

package org.mobicents.protocols.ss7.map.api.service.mobility.subscriberInformation;

import java.io.Serializable;

/**
 *
 GPRSChargingID ::= OCTET STRING (SIZE (4)) -- The Charging ID is a unique four octet value generated by the GGSN when -- a
 * PDP Context is activated. A Charging ID is generated for each activated context. -- The encoding is defined in 3GPP TS
 * 29.060.
 *
 *
 * @author sergey vetyutnev
 *
 */
public interface GPRSChargingID extends Serializable {

    byte[] getData();

}
