[[_setup_running]]
= Installing {this-platform} {this-application} 

== Installation Options

The {this-platform} {this-application} is logically divided into two sections - lower and upper.
The lower section provides implementation for SS7 Level 2 and Level 3 and is therefore influenced by the type of SS7 hardware (Level 1) used.
The upper section provides implementation for SS7 Level 4 and above. {this-platform} {this-application} gives you the flexibility to install and use the Levels 2,3 and 4 in the same JVM and machine where SS7 Hardware (Level 1) is installed.
Alternately, you can also install Level 1,2 and 3 in one machine and install Level 4 on a separate machine.
In the second scenario, `M3UA` over `SCTP` is used for communication between Level 3 and Level 4 (on different machines) and this is referred to as {this-platform}  Signaling Gateway.

{this-platform} {this-application} can be installed to function as a standalone component if you do not wish to use JBoss Application Server.
However if you intend to use JSLEE Resource Adaptors or Shell (CLI), then you must deploy it as a JBoss AS Service.
The sections below provide instructions for installing the Stack for use with JBoss AS or as a standalone component. 

[[_running_with_jboss]]
=== {this-platform} {this-application}  as a JBoss AS Service

{this-platform} SS7 Service can be deployed in any container that supports `JMX` and exposes `JNDI`.
By using the {this-platform}  SS7 Service you will be able to configure the SS7 stack using CLI (Command Line Interface) commands.
The SS7 Service wraps SS7 Level 4 (i.e., MAP, CAP and ISUP) and the lower layers and exposes via JNDI, such that the layer above can perform the look-up and use it in any application.
 

.Procedure: Installing {this-platform} SS7 Service to JBoss 5.1.0.GA

. Pre-Requisites:
+
* The {this-platform} SS7 Service binary requires that you have JBoss Application Server installed and `JBOSS_HOME` Environment variable set properly. The latest binaries of JBoss Application Server can by obtained from {slee2-binary-url}. For more details on setting the `JBOSS_HOME` variable, please refer to the section <<_jboss_home_setup>>.
* `Ant 1.9` (or higher) must be used to install the binary.
  Instructions for using Ant, including install, can be found at http://ant.apache.org/.
* If you are using the SS7 board on server, you must ensure that the `java.library.path` variable is set to point to the directory containing the native component.
  Alternatively you can copy it to the JBoss native library path manually. 

. Deploying the SS7 Service:
+
* You can now deploy the service using the `ant deploy` command as shown below: 
+
[source,subs="attributes"]
----
[usr1]$ cd {path}/ss7-jboss
[usr1]$ ant deploy
----      

. Result:
+
* If the service has been deployed successfully, you will find the below message appear on screen:
+
[source,subs="attributes"]
----

Buildfile: ../{path}/ss7-jboss/build.xml

deploy:
     [copy] Copying 47 files to JBOSS_HOME/server/default/deploy/restcomm-ss7-service
     [copy] Copying 2 files to JBOSS_HOME/bin
     [copy] Copying 11 files to JBOSS_HOME/lib
     [copy] Copying 2 files to JBOSS_HOME/server/default/deploy

BUILD SUCCESSFUL
----

* You have now deployed {this-platform} SS7 Service successfully.
  Note that this procedure will also install the Shell Components (shell scripts and libraries) on this machine.

.Procedure: Installing {this-platform} SS7 Service to WildFly 10.1.0.Final

. Pre-Requisites:
+
* The {this-platform} SS7 Service binary requires that you have WildFly installed and `JBOSS_HOME` Environment variable set properly. The latest binaries of WildFly can by obtained from {slee7-binary-url}. For more details on setting the `JBOSS_HOME` variable, please refer to the section <<_jboss_home_setup>>.
* `Ant 1.9` (or higher) must be used to install the binary.
  Instructions for using Ant, including install, can be found at http://ant.apache.org/.
* If you are using the SS7 board on server, you must ensure that the `java.library.path` variable is set to point to the directory containing the native component.
  Alternatively you can copy it to the JBoss native library path manually.

. Deploying the SS7 Service:
+
* You can now deploy the service using the `ant deploy` command as shown below:
+
[source,subs="attributes"]
----
[usr1]$ cd {path}/ss7-wildfly
[usr1]$ ant deploy
----

. Result:
+
* If the service has been deployed successfully, you will find the below message appear on screen:
+
[source,subs="attributes"]
----

Buildfile: ../{path}/ss7-wildfly/build.xml

deploy:
     [copy] Copying 48 files to JBOSS_HOME/modules/system/layers/base/org/mobicents/ss7
     [copy] Copying 2 files to JBOSS_HOME/bin
     [copy] Copying 11 files to JBOSS_HOME/lib
     [copy] Copying 2 files to JBOSS_HOME/standalone/deployments

BUILD SUCCESSFUL
----

* You have now deployed {this-platform} SS7 Service successfully.
  Note that this procedure will also install the Shell Components (shell scripts and libraries) on this machine.


[[_restcomm_ss7_sgw]]
=== {this-platform} {this-application}  as a Signaling Gateway

{this-platform} {this-application} can function as a standalone Signaling Gateway installed on any machine.
It acts as a signaling agent that receives/sends Switched Circuit Network (SCN) native signaling at the edge of an IP network.
Installing the Signaling Gateway is straightforward. 

.Procedure: Installing Signaling Gateway
. Pre-Requisites:
+
* You must have JDK 1.7 and lksctp library installed on your machine. 

. Copy [path]_{this-platform}-{this-application}-{project-version}/ss7/{this-folder}-ss7-sgw_ to any folder of your choice in any machine that supports the requirements specified.
  Your Signaling Gateway is now ready to be used.


[[_restcomm_ss7_shell]]
=== Shell - Command Line Interface (CLI)

Once you have installed {this-platform} SS7 Service and the Signaling Gateway, you can configure and manage them both using Shell commands. {this-platform} {this-application} comes with a Shell Management Interface that enables easy run-time configuration.
You can install the Shell (CLI) Component on any machine (usually remote) and easily connect to and manage the Stack on a remote machine with simple commands.
For more details on using the Shell and the commands available, please refer to the {this-platform} {this-application} User Guide. 

.Procedure: Installing CLI
. Pre-Requisites
+
* You must have JBoss Application Server installed and `JBOSS_HOME` Environment variable set properly.
  For more details on setting the `JBOSS_HOME` variable, please refer to the section <<_jboss_home_setup>>. 
* `Ant 1.9` (or higher) must be used to install the binary.
  Instructions for using Ant, including install, can be found at http://ant.apache.org/.

. Copy [path]_{this-platform}-{this-application}-{project-version}/ss7_ to any folder of your choice in any machine that supports the requirements specified. 
. You can now deploy using the `ant deploy` command as shown below: 
+
[source]
----
[usr1]$ cd -/ss7
[usr1]$ ant deploy
----      
. Result:
+
* If the Shell has been deployed successfully, you will find the below message appear on screen:
+
[source]
----

Buildfile: /home/vinu/Downloads/restcomm-jss7-3.0.0/ss7/build.xml

deploy:
     [copy] Copying 38 files to /home/vinu/Downloads/restcomm-jss7-3.0.0/ss7/${system.JBOSS_HOME}/server/default/deploy/restcomm-ss7-service
     [copy] Copying 2 files to /home/vinu/Downloads/restcomm-jss7-3.0.0/ss7/${system.JBOSS_HOME}/bin
     [copy] Copying 9 files to /home/vinu/Downloads/restcomm-jss7-3.0.0/ss7/${system.JBOSS_HOME}/lib

BUILD SUCCESSFUL
----

* You have now deployed the Shell Components (shell scripts and libraries) successfully on this machine.
  You can now Start the Shell and connect it to any SS7 service instance and manage the Stack from the Command Line.


[[_restcomm_ss7_simulator]]
=== Installing the {this-platform} {this-application}  Simulator

{this-platform} {this-application} Simulator can function as a standalone component installed on any machine.
The Simulator module will enable you to test and understand the functionality of the Stack.
 

.Procedure: Installing Simulator
. Pre-Requisites:
+
* You must have JDK 1.7 installed on your machine. 

. Copy [path]_{this-platform}-{this-application}-{project-version}/ss7/{this-folder}-ss7-simulator_  to any folder of your choice in any machine that supports the requirements specified.
  Your Simulator is now ready to be used.

[[_running_without_jboss]]
=== {this-platform} {this-application}  as a Standalone Component

{this-platform} {this-application} can be installed as a standalone Java library without any dependency on JBoss, {this-platform} JSLEE or any other container.
The {this-platform} {this-application} User Guide will assist you in implemeting this and also give some details of how jSS7 layers can be configured.
If you do not intend to use it with JBoss AS, then you must follow the regular way of initializing jSS7 Stack, which is to build each of the protocols, configure individually and bind them together. 


[[_restcomm_ss7_install_hardware_libraries]]
== Installing of hardware native libraries.

If you use hardware SS7 cards you need to make extra actions for installing of hardware native libraries. A hardware SS7 card must be already installed (refer to the section <<_setup_hardware>>).


[[_restcomm_ss7_install_hardware_libraries_dahdi]]
=== Installing of hardware native libraries for dahdi cards.

Follow steps for installing of native libraries dahdi cards:

* We have the driver only for 32-bit JAVA for linux. Other OS and 64-bit is not supported.
* We need to have `JAVA 7` and `GCC` compiler installed
* Download latest dahdi complete from their site
http://downloads.asterisk.org/pub/telephony/dahdi-linux-complete/
and unzip it
* Copy "dahdi_config.h" and "user.h"
from the unzipped folder like: `dahdi-linux-complete-<version>/linux/include/dahdi/`
to the linux "include" folder: `/usr/include/dahdi` (in case when linux "include" files are located in `/usr/include` folder)
* Compile dahdi native lib - run from the folder of downloaded jss7 sources (how to download source code - check <<_source_code>>) `jss7/hardware/dahdi` by the command:
`mvn install -Pdahdilinux -Dinclude.zap=/usr/include/dahdi`
* Copy the compiled native lib "libmobicents-dialogic-linux.so" from `jss7/hardware/dahdi/native/linux/target` folder to
** `jboss-5.1.0.GA/bin/META-INF/lib/linux2/x86` folder if you run JSS7 under jboss
** other folder where JSS7 will search a native lib in case of a stand-alone usage
* in JBOSS case by default "jboss-beans.xml" config file in the jboss deploy folder (the folder like `jboss-5.1.0.GA/server/default/deploy/{this-platform}-ss7-service/META-INF`)
is configured to use m3ua stack by default. If you want to use SS7 hardware cards you need to update it - update the definition of bean "Mtp3UserPart" to the corresponded hardware depended bean.


[[_restcomm_ss7_install_hardware_libraries_dialogic]]
=== Installing of hardware native libraries for dialogic cards.

Follow steps for installing of native libraries dialogic cards:

* Download latest DSI Software from https://www.dialogic.com/en/products/signaling-and-ss7-components/download/dsi-interface-protocol-stacks.aspx and unzip it (it may be already done during the hardware installation procedure)
* copy the native library "libgctjni.so"
** for 32-bit JAVA: from subfolder `32` to jboss folder `jboss-5.1.0.GA/bin/META-INF/lib/linux2/x86` or other folder where JSS7 will search a native lib in case of a stand-alone usage
** for 64-bit JAVA: from subfolder `64` to jboss folder `jboss-5.1.0.GA/bin/META-INF/lib/linux2/x64` or other folder where JSS7 will search a native lib in case of a stand-alone usage
* copy the gctApi library "gctApi.jar" from subfolder `JAVA` to the folder where JSS7 stack jar files are deployed.
** In JBOSS case the target folder may be folder `jboss-5.1.0.GA/server/default/deploy/{this-platform}-ss7-service/lib` for the default profile and `jboss-5.1.0.GA/server/simulator/deploy/{this-platform}-ss7-service/lib` for the simulator profile.
** For products like SMSC GW, USSD GW, CAMEL GW, GMLC the target folder will be the folders like `jboss-5.1.0.GA/server/default/deploy/{this-platform}-smsc-server/lib` for the default profile and `jboss-5.1.0.GA/server/simulator/deploy/{this-platform}-smsc-server/lib` for the simulator profile.
** For stand-alone installation the target folder is where SS7 stack jars are deployed
* in JBOSS case by default "jboss-beans.xml" config file in the jboss deploy folder (the folder like `jboss-5.1.0.GA/server/default/deploy/{this-platform}-ss7-service/META-INF`)
is configured to use m3ua stack by default. If you want to use SS7 hardware cards you need to update it - update the definition of bean "Mtp3UserPart" to the corresponded hardware depended bean. Examples of jboss-beans.xml you can find in the following folders (you can just these files to `META-INF` folder):
** for usage only a Dialogic board without m3ua (sigtran) - `ss7/template/META-INF-dialogic`
** for usage a Dialogic board together with m3ua (sigtran) - `ss7/template/META-INF-m3ua-dialogic`


[[_setup_configuration]]
== Post Installation Configuration

Now that you have installed {this-platform} {this-application} to suit your needs, you can go ahead and configure the Stack to meet your requirements.
The User Guide (available along with this Installation Guide) in the [path]_{this-platform}-{this-application}-{project-version}/docs_ folder will assist you in configuring and managing the Stack.
The Shell Management module will enable you to easily configure the Stack using the Command Line Interface (CLI) tool. 

=== Memory Settings

You should fine tune the JVM memory settings based on your needs but we recommend you allocate a minimum of 3 GB for initial and maximum heap size. 

-Xms3072m::
  Initial heap size, set in megabytes

-Xmx3072m::
  Maximum heap size, set in megabytes
