[[_setup_downloading]]

= Downloading

Installing {this-platform} {this-application} is easy and quick with the binary download.
You can either download the binary release or download the source code and set up from source.

[[_downloading_binary]]
== Binary Download

The binary release is available for download at the following link: {this-release-binary-url}

.Procedure: Binary Download
. Download the zip file _{path}.zip_ to any folder of your choice.
. Extract the contents of the zip file. 
+

[source,subs="attributes"]
----
Downloads]$ unzip {path}.zip
----						
. Verify the contents of the newly created directory.

When you download the binary release, you will notice that the top level directory is named _{path}_ and immediately below this are 7 sub-directories named _asn_, __docs_, _oam_, _sctp_, _ss7_, _ss7-jboss_ and _ss7-wildfly_ encompassing the major services and libraries that make up {this-platform}  {this-application} .
For details on what is included in the sub-directories, please refer to the {this-platform}  {this-application}  User Guide. 

The major functional modules of the {this-application} are: 

. SS7 Service [dir: _{this-folder}-ss7-service_]
. Signaling Gateway [dir: _{this-folder}-ss7-sgw_]
. Shell [dir: _shell_]
. SS7 Simulator [dir: _{this-folder}-ss7-simulator_]

[subs="attributes"]
----

|- {this-folder}-jss7-{project-version}
		|- asn	

		|- _docs
	
		|- oam

		|- sctp	

		|- ss7
				|+ protocols
				|+ shell
				|+ {this-folder}-ss7-simulator
				|+ {this-folder}-ss7-trace-parser

		|- ss7-jboss
				|+ {this-folder}-ss7-service
				|+ {this-folder}-ss7-sgw
				|+ template

		|- ss7-wildfly
                |+ {this-folder}-ss7-service
                |+ template

----

[[_source_code]]
== Setup from Source 

{this-platform} {this-application} is an open source project and you have the freedom to build from source.
Building from source means you can stay on top with the latest features.
Whilst aspects of {this-platform} {this-application} are quite  complicated, you may find ways to become contributors.

{this-platform} {this-application} works with JDK1.7 or above.
In addition you must have the following tools installed.

.Pre-Requisites for Building from Source

* `Git Client` : Instructions for using GIT, including install, can be found at http://git-scm.com/book
* `Maven 3.2.X` : Instructions for using Maven, including install, can be found at http://maven.apache.org/
* `Ant 1.9.X` : Instructions for using Ant, including install, can be found at http://ant.apache.org
* `jmxtools:jar` :  This library is required to build the Simulator source code. The library com.sun.jdmk:jmxtools:jar:1.2.1 must be downloaded manually and placed in your maven repository. Instructions are provided below.

Instructions to Download `jmxtools:jar` for building Simulator source code are as follows: 

* The file can be downloaded from Oracle's website.
  The link is: http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-java-plat-419418.html#7657-jmx-1.2.1-oth-JPR&usg=AFQjCNGOqUaCB1ULVG7cMULio9u70MKocA. 
* The webpage will display a list of Java Platform Technology Downloads.
  From the list, select "Java Management Extension (JMX) 1.2.1" 
* Read and understand the License Agreement and then press "Accept License Agreement". 
* Download the _jmx-1_2_1-ri.zip_ file.
* Extract _lib/jmxtools:jar_
* Once extracted, place this file in your maven repository as _.m2/repository/com/sun/jdmk/jmxtools/1.2.1/jmxtools-1.2.1.jar_ file if _.m2/repository_ is a root of this repository.
  Alternatively you can register it. 

[[_source_building]]
=== Release Source Code Building


. Downloading the source code
+
Checkout a specific release source using GIT.
The base URL to clone from is {this-release-source-code-url}.
Then add the specific release version, in the below example we are downloading the version {project-version}.
+
[source,subs="attributes"]
----
[usr]$ git clone {this-release-source-code-url} jss7
[usr]$ cd jss7
[usr]$ git checkout <version>
----

. Building the source code
+
Now that we have the source code, the next step is to build and install the source. {this-platform} {this-application} uses Maven 3 to build the system.
There are two build profiles namely default and dahdilinux.
The Default profile builds only the java source code.
The profile "dahdilinux" compile relevant native modules in addition to building the java source. 
+
NOTE: At the moment, native modules are supported only for Linux OS. 
+
* Building using "default" Build profile
+
To build {this-platform} {this-application} without building any native libraries use the default profile as shown below.
+
[source,subs="attributes"]
----
[usr]$ cd jss7
[usr]$ mvn install
----
+
NOTE: If you are using {this-platform} {this-application} without any native dependencies, {this-platform} {this-application} can run on any OS. 

* Building using "dahdilinux" profile
+
Use this profile only if the linux server on which this code is built has `dahdi` module installed.
Make sure you pass the "include.zap" system property with a value pointing to the directory where `dahdi` is installed
+
[source,subs="attributes"]
----
[usr]$ cd jss7
[usr]$ mvn install -Pdahdilinux -Dinclude.zap=/usr/include/dahdi
----


. Use Ant to build the binary.
+
[source,subs="attributes"]
----
[usr]$ cd jss7/release
[usr]$ ant
----


[[_trunk_source_building]]
=== Development Trunk Source Building

To build from development trunk source, follow the same procedure as above but at the time of checkout do not switch to the specific release tag. 
[source,subs="attributes"]
----
[usr]$ git clone {this-release-source-code-url} jss7
[usr]$ cd jss7
[usr]$ git checkout
----  
The rest of the steps are as outlined in the above section <<_source_building>>		 
