[[_setup_hardware]]
= Hardware Setup

You do not require any specific hardware if you intend to use only SIGTRAN (M3UA). But if you wish to use legacy SS7 links, then you must have relevant SS7 cards installed along with their native libraries. 

{this-platform} {this-application} supports `dahdi` based SS7 cards like `diguim` and `sangoma` as well as `dialogic` cards.
Since `dahdi` based SS7 cards do not have MTP2/MTP3 support on board they rely on external software to provide these services.
But `dialogic` based SS7 cards have on board support for MTP2/MTP3 and recommended. 

This guide does not provide installation instructions for SS7 hardware.
You must refer to respective vendor documentation for installing and configuring the hardware cards.
The following external links point to information that will assist you in setting up the hardware.
 

* Sangoma: http://wiki.sangoma.com/
* Diguim: http://www.digium.com/en/products/digital/
* Dialogic: http://www.dialogic.com/

[NOTE]
====
Before JSS7 stack can interoperate with an installed card you need to provide extra native libs for both Dialogic and dahdi cards. The way where you can obtain native libs is explained in <<_restcomm_ss7_install_hardware_libraries>>.
====
