[[_configuring_standalone]]
= Configuring as a Standalone library

If you intend to use the Stack as a standalone library without using JBoss Application Server or JSLEE RAs, then you must manually build each of the protocols, configure them individually, and bind them together.

[[_standalone_sctp]]
== Building SCTP

This is an example of a typical SCTP startup procedure, in one line of code, using automatic configuration file detection:  
[source]
----
    org.mobicents.protocols.api.Management sctpManagement = null;
    sctpManagement = new org.mobicents.protocols.sctp.netty.NettySctpManagementImpl("Client");
    sctpManagement.setPersistDir("<your directory path>");

    sctpManagement.start();

    sctpManagement.setConnectDelay(10000);
----

How did jSS7 know where the configuration file was located and which one to load?  

When `sctpManagement.start()` is called, jSS7 searches for a file named [path]_Client_sctp.xml_ in the directory path set by user by calling  `sctpManagement.setPersistDir("<your directory path>")`.
For example in case of linux you can pass something like  `this.sctpManagement.setPersistDir("/home/abhayani/workarea/mobicents/git/jss7/master/map/load/client")`.
If directory path is not set, Management searches for system property  `sctp.persist.dir` to get the path for directory.
Even if `sctp.persist.dir` system property is not set, Management will look at System set property  `user.dir`.

Once you know SCTP layer is configured and started, you can set Stack level parameters like `connectionDelay` by calling setters like: `sctpManagement.setConnectDelay(10000);`

Next step is adding of the Association and/or Server depending on whether this setup will be acting as client or server or both. Normally a configured set of Association and/or Server are stored in the xml config file and this way is recommended. But if you want to remove all previously configured Associations and Servers you need to call this command (after a Stack start).
[source]
----
    sctpManagement.removeAllResourses();
----

Before adding server side association the server should also be defined and started as below: 
[source]
----
    boolean acceptAnonymousConnections = false;
    int maxConcurrentConnectionsCount = 0; // for AnonymousConnections, 0 means unlimited
    String[] extraHostAddresses = null; // for multi-homing
    IpChannelType ipChannelType = IpChannelType.SCTP;

    sctpManagement.addServer(SERVER_NAME, SERVER_IP, SERVER_PORT, ipChannelType, acceptAnonymousConnections, maxConcurrentConnectionsCount, extraHostAddresses);
    sctpManagement.addServerAssociation(PEER_IP, PEER_PORT, SERVER_NAME, SERVER_ASSOCIATION_NAME, ipChannelType);
    sctpManagement.startServer(SERVER_NAME);
----				

For Client side association the code is the following:
[source]
----
    String[] extraHostAddresses = null; // for multi-homing
    IpChannelType ipChannelType = IpChannelType.SCTP;

    sctpManagement.addAssociation(HOST_IP, HOST_PORT, PEER_IP, PEER_PORT, CLIENT_ASSOCIATION_NAME, ipChannelType, extraHostAddresses);
----

NOTE: You should never start the Association programatically.
Association will be started automatically when layer above M3UA's ASP is started. 				

This completes the SCTP configuration and start-up. 

[[_building_m3ua_standalone]]
== Building M3UA

Configuring the M3UA layer is similar to the steps followed for SCTP. 
[source]
----
    org.mobicents.protocols.ss7.m3ua.impl clientM3UAMgmt = null;
    clientM3UAMgmt = new M3UAManagement("Client", null);
    clientM3UAMgmt.setPersistDir("<your directory path>");
    clientM3UAMgmt.setTransportManagement(sctpManagement);
    clientM3UAMgmt.setDeliveryMessageThreadCount(DELIVERY_TRANSFER_MESSAGE_THREAD_COUNT);

    clientM3UAMgmt.start();
----			

For M3UA, it should know which underlying SCTP layer to use `clientM3UAMgmt.setTransportManagement(sctpManagement);`. 

Once M3UA is configured and started, next step is to add the As, Asp and routing rules for M3UA. Configured set of As, Asp and routing rules is trored in [path]_Client_m3ua1.xml_ (in "your directory path" folder). But if you want to remove all previously configured As, Asp and routing rules you need to call this command (after a Stack start).
[source]
----
    clientM3UAMgmt.removeAllResourses();
----

A set of As, Asp and routing rules depends on whether stack acts as Application Server side or Signaling Gateway side or just  peer-to-peer (IPSP) client/server side.
Below is an example of IPSP peer acting as client. 
[source]
----
    ParameterFactoryImpl factory = new ParameterFactoryImpl();

    // Step 1 : Create App Server
    RoutingContext rc = factory.createRoutingContext(new long[] { 100l });
    TrafficModeType trafficModeType = factory.createTrafficModeType(TrafficModeType.Loadshare);
    As as = clientM3UAMgmt.createAs("AS1", Functionality.AS, ExchangeType.SE, IPSPType.CLIENT, rc, trafficModeType, 1, null);

    // Step 2 : Create ASP
    AspFactory aspFactor = clientM3UAMgmt.createAspFactory("ASP1", CLIENT_ASSOCIATION_NAME);

    // Step3 : Assign ASP to AS
    Asp asp = clientM3UAMgmt.assignAspToAs("AS1", "ASP1");

    // Step 4: Add Route. Remote point code is 2
    clientM3UAMgmt.addRoute(SERVET_SPC, -1, -1, "AS1");
----			

This completes the M3UA configuration and start-up.
Once M3UA is configured depending on whether you are trying to build voice application that depends on ISUP or  advanced network features such as those offered by supplementary services that depends on MAP, you would configure ISUP or SCCP  

== Building SCCP

Configuring the SCCP layer follows exactly same architecture of persisting configuration in xml file.
 
[source]
----
    org.mobicents.protocols.ss7.sccp.SccpStack sccpStack = null;
    sccpStack = new SccpStackImpl("MapLoadClientSccpStack");
    clientM3UAMgmt.setPersistDir("<your directory path>");
    sccpStack.setMtp3UserPart(1, this.clientM3UAMgmt);

    sccpStack.start();
----		

Before starting SCCP stack all it needs to know is underlying MTP3 layer.
Above sections explained building SCTP and M3UA,  however if you are using Dialogic boards or dahdi based boards (Diguim/Sangoma), you need to build and configure respective MTP3 layers depending on hardware used and set those in SCCP Stack `sccpStack.setMtp3UserPart(1, this.clientM3UAMgmt)`.
 

One of the best features of jSS7 is it supports multiple MTP3 layers and hence you can have combination of many MTP3 layers (each of different or same type like M3UA, Dialogic and Dahid;  all used at same time). 

Once SCCP stack is started, it should be configured for local and remote signaling point-code, network indicator, remote sub system number and routing rules. For removing all previously configured resources you need to call this command (after a Stack start).
[source]
----
    sccpStack.removeAllResourses();
----

Here is an example for adding resources:
[source]
----
    sccpStack.getSccpResource().addRemoteSpc(0, SERVET_SPC, 0, 0);
    sccpStack.getSccpResource().addRemoteSsn(0, SERVET_SPC, SSN, 0, false);

    sccpStack.getRouter().addMtp3ServiceAccessPoint(1, 1, CLIENT_SPC, NETWORK_INDICATOR, 0);
    sccpStack.getRouter().addMtp3Destination(1, 1, SERVET_SPC, SERVET_SPC, 0, 255, 255);

    ParameterFactoryImpl fact = new ParameterFactoryImpl();
    EncodingScheme ec = new BCDEvenEncodingScheme();
    GlobalTitle gt1 = fact.createGlobalTitle("-", 0, org.mobicents.protocols.ss7.indicator.NumberingPlan.ISDN_TELEPHONY, ec, NatureOfAddress.INTERNATIONAL);
    GlobalTitle gt2 = fact.createGlobalTitle("-", 0, org.mobicents.protocols.ss7.indicator.NumberingPlan.ISDN_TELEPHONY, ec, NatureOfAddress.INTERNATIONAL);
    SccpAddress localAddress = new SccpAddressImpl(RoutingIndicator.ROUTING_BASED_ON_GLOBAL_TITLE, gt1, CLIENT_SPC, 0);
    sccpStack.getRouter().addRoutingAddress(1, localAddress);
    SccpAddress remoteAddress = new SccpAddressImpl(RoutingIndicator.ROUTING_BASED_ON_GLOBAL_TITLE, gt2, SERVET_SPC, 0);
    sccpStack.getRouter().addRoutingAddress(2, remoteAddress);

    GlobalTitle gt = fact.createGlobalTitle("*", 0, org.mobicents.protocols.ss7.indicator.NumberingPlan.ISDN_TELEPHONY, ec, NatureOfAddress.INTERNATIONAL);
    SccpAddress pattern = new SccpAddressImpl(RoutingIndicator.ROUTING_BASED_ON_GLOBAL_TITLE, gt, 0, 0);
    sccpStack.getRouter().addRule(1, RuleType.SOLITARY, LoadSharingAlgorithm.Bit0, OriginationType.REMOTE, pattern, "K", 1, -1, null, 0);
    sccpStack.getRouter().addRule(2, RuleType.SOLITARY, LoadSharingAlgorithm.Bit0, OriginationType.LOCAL, pattern, "K", 2, -1, null, 0);
----		

Once SCCP is configured and started, next step it to build TCAP layer.

== Building TCAP

There is no configuration to persist in case of TCAP. 
[source]
----
    org.mobicents.protocols.ss7.tcap.api tcapStack = null;
    tcapStack = new TCAPStackImpl("Client", this.sccpStack.getSccpProvider(), SSN);

    tcapStack.start();

    this.tcapStack.setDialogIdleTimeout(60000);
    this.tcapStack.setMaxDialogs(MAX_DIALOGS);
----  

Configuring TCAP is probably very simple as config reamins same irrespective of whether its used on client side or server side.
 

== Building MAP

There is no configuration to persist in case of MAP; however MAP stack can take TCAPProvider from TCAPStack which is already configured for specific SSN as shown below: 
[source]
----
    mapStack = new MAPStackImpl("Client", tcapStack.getProvider());
----			
Or it can also directly take SccpProvider and pass SSN to MAP Stack as shown below.
In this case MAPStack itself creates the TCAPStack and leverages TCAPProvider: 
[source]
----
    mapStack = new MAPStackImpl("Client", sccpStack.getSccpProvider(), SSN);
----		

Before MAPStack can be started, the Application interested in particualr MAP Service should register it-self as listener and activate that service: 
[source]
----
    mapProvider = mapStack.getMAPProvider();
    mapProvider.addMAPDialogListener(this);
    mapProvider.getMAPServiceSupplementary().addMAPServiceListener(this);
    mapProvider.getMAPServiceSupplementary().acivate();
    mapStack.start();
----		

Below is how the Application code looks like: 
[source]
----
    public class Client extends MAPDialogListener, MAPServiceSupplementaryListener  {
        //Implemet all MAPDialogListener methods here

        //Implement all MAPServiceSupplementaryListener methods here
    }
----		

== Common Code

All above snippet of code refers to below defined constants:

[source]
----
    // MTP Details
    protected final int CLIENT_SPC = 1;
    protected final int SERVET_SPC = 2;
    protected final int NETWORK_INDICATOR = 2;
    protected final int SERVICE_INIDCATOR = 3; //SCCP
    protected final int SSN = 8;

    protected final String CLIENT_IP = "127.0.0.1";
    protected final int CLIENT_PORT = 2345;

    protected final String SERVER_IP = "127.0.0.1";
    protected final int SERVER_PORT = 3434;

    protected final int ROUTING_CONTEXT = 100;

    protected final String SERVER_ASSOCIATION_NAME = "serverAsscoiation";
    protected final String CLIENT_ASSOCIATION_NAME = "clientAsscoiation";

    protected final String SERVER_NAME = "testserver";

    .....
    .....
----

Once you have completed development of your application, next thing is setting the classpath, compiling and starting application.
You must set the classpath to point to  {this-folder}-jss7-X.Y.Z/ss7/{this-folder}-ss7-service/lib.
It has all the libraries needed to compile and start your application.
Don't forget to include your compiled Application class file in classpath before starting the Application.
 
