/*
 * TeleStax, Open Source Cloud Communications
 * Copyright 2011-2013, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

package org.mobicents.protocols.ss7.tcapAnsi.api.asn.comp;

import org.mobicents.protocols.ss7.tcapAnsi.api.asn.DialogPortion;
import org.mobicents.protocols.ss7.tcapAnsi.api.asn.Encodable;
import org.mobicents.protocols.ss7.tcapAnsi.api.asn.UserInformationElement;

/**
 *
 * @author baranowb
 * @author sergey vetyutnev

Abort ::= SEQUENCE {
    identifier          TransactionID,
    dialogPortion       DialoguePortion OPTIONAL,
    causeInformation    CHOICE {
        abortCause          P-Abort-cause,
        userInformation     UserAbortInformation    OPTIONAL
    }
}
--When the Abort package is generated by the Transaction sublayer,
--the P-Abort-cause must be present

 *
 */
public interface TCAbortMessage extends Encodable {

    int _TAG_ABORT = 22;
    int _TAG_P_ABORT_CAUSE = 23;
    int _TAG_USER_ABORT_INFORMATION = 24;

    byte[] getDestinationTransactionId();

    void setDestinationTransactionId(byte[] t);

    DialogPortion getDialogPortion();

    void setDialogPortion(DialogPortion dp);

    PAbortCause getPAbortCause();

    void setPAbortCause(PAbortCause t);

    UserInformationElement getUserAbortInformation();

    void setUserAbortInformation(UserInformationElement uai);

}
