package org.mobicents.protocols.ss7.tcap.api.tc.dialog.events;

import org.mobicents.protocols.ss7.tcap.asn.AbortSource;
import org.mobicents.protocols.ss7.tcap.asn.UserInformation;

/**
 * <pre>
 * -- NOTE – When the Abort Message is generated by the Transaction sublayer, a p-Abort Cause must be
 * -- present.The u-abortCause may be generated by the component sublayer in which case it is an ABRT
 * -- APDU, or by the TC-User in which case it could be either an ABRT APDU or data in some user-defined
 * -- abstract syntax.
 * </pre>..................
 * @author amit bhayani
 * @author baranowb
 */
public interface TCUserAbortIndication extends DialogIndication {


	//User defined data, anything... if this is set, it coded as dialogue portion
	//public External getAbortReason()

	public UserInformation getUserInformation();
	public AbortSource getAbortSource();

}
